BUG: Update test to fix conversion of vtk.mutable to int
This commit fixes error like the following error:

  TypeError: type str doesn't define __trunc__ method